-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgkUABD7BGnULcEnuY
IGAkfqhsROvG8QfRx5IbAjEOiTSgCgYIKoZIzj0DAQehRANCAAQKHQ3eY3piEOa2
QO8rai1ChWRw3gfyr1K8L4c38HPV5vmjlOqhbSwvpPN4LVSzXLmYf/LeOVvsU+1v
5au5dEWW
-----END PRIVATE KEY-----